# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ybleile/correa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ybleile/correa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ybleile/correa/CMakeFiles /home/ybleile/correa//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ybleile/correa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _correa

# Build rule for target.
_correa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 _correa
.PHONY : _correa

# fast build rule for target.
_correa/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_correa.dir/build.make CMakeFiles/_correa.dir/build
.PHONY : _correa/fast

#=============================================================================
# Target rules for targets named nanobind-static

# Build rule for target.
nanobind-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nanobind-static
.PHONY : nanobind-static

# fast build rule for target.
nanobind-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/build
.PHONY : nanobind-static/fast

#=============================================================================
# Target rules for targets named 2DShape

# Build rule for target.
2DShape: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 2DShape
.PHONY : 2DShape

# fast build rule for target.
2DShape/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/2DShape.dir/build.make src/CMakeFiles/2DShape.dir/build
.PHONY : 2DShape/fast

#=============================================================================
# Target rules for targets named Comp2DShapes

# Build rule for target.
Comp2DShapes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Comp2DShapes
.PHONY : Comp2DShapes

# fast build rule for target.
Comp2DShapes/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Comp2DShapes.dir/build.make src/CMakeFiles/Comp2DShapes.dir/build
.PHONY : Comp2DShapes/fast

#=============================================================================
# Target rules for targets named Comp2DShapesFocal

# Build rule for target.
Comp2DShapesFocal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Comp2DShapesFocal
.PHONY : Comp2DShapesFocal

# fast build rule for target.
Comp2DShapesFocal/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/Comp2DShapesFocal.dir/build.make src/CMakeFiles/Comp2DShapesFocal.dir/build
.PHONY : Comp2DShapesFocal/fast

ext/nanobind/src/common.o: ext/nanobind/src/common.cpp.o
.PHONY : ext/nanobind/src/common.o

# target to build an object file
ext/nanobind/src/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/common.cpp.o
.PHONY : ext/nanobind/src/common.cpp.o

ext/nanobind/src/common.i: ext/nanobind/src/common.cpp.i
.PHONY : ext/nanobind/src/common.i

# target to preprocess a source file
ext/nanobind/src/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/common.cpp.i
.PHONY : ext/nanobind/src/common.cpp.i

ext/nanobind/src/common.s: ext/nanobind/src/common.cpp.s
.PHONY : ext/nanobind/src/common.s

# target to generate assembly for a file
ext/nanobind/src/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/common.cpp.s
.PHONY : ext/nanobind/src/common.cpp.s

ext/nanobind/src/error.o: ext/nanobind/src/error.cpp.o
.PHONY : ext/nanobind/src/error.o

# target to build an object file
ext/nanobind/src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/error.cpp.o
.PHONY : ext/nanobind/src/error.cpp.o

ext/nanobind/src/error.i: ext/nanobind/src/error.cpp.i
.PHONY : ext/nanobind/src/error.i

# target to preprocess a source file
ext/nanobind/src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/error.cpp.i
.PHONY : ext/nanobind/src/error.cpp.i

ext/nanobind/src/error.s: ext/nanobind/src/error.cpp.s
.PHONY : ext/nanobind/src/error.s

# target to generate assembly for a file
ext/nanobind/src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/error.cpp.s
.PHONY : ext/nanobind/src/error.cpp.s

ext/nanobind/src/implicit.o: ext/nanobind/src/implicit.cpp.o
.PHONY : ext/nanobind/src/implicit.o

# target to build an object file
ext/nanobind/src/implicit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/implicit.cpp.o
.PHONY : ext/nanobind/src/implicit.cpp.o

ext/nanobind/src/implicit.i: ext/nanobind/src/implicit.cpp.i
.PHONY : ext/nanobind/src/implicit.i

# target to preprocess a source file
ext/nanobind/src/implicit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/implicit.cpp.i
.PHONY : ext/nanobind/src/implicit.cpp.i

ext/nanobind/src/implicit.s: ext/nanobind/src/implicit.cpp.s
.PHONY : ext/nanobind/src/implicit.s

# target to generate assembly for a file
ext/nanobind/src/implicit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/implicit.cpp.s
.PHONY : ext/nanobind/src/implicit.cpp.s

ext/nanobind/src/nb_enum.o: ext/nanobind/src/nb_enum.cpp.o
.PHONY : ext/nanobind/src/nb_enum.o

# target to build an object file
ext/nanobind/src/nb_enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_enum.cpp.o
.PHONY : ext/nanobind/src/nb_enum.cpp.o

ext/nanobind/src/nb_enum.i: ext/nanobind/src/nb_enum.cpp.i
.PHONY : ext/nanobind/src/nb_enum.i

# target to preprocess a source file
ext/nanobind/src/nb_enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_enum.cpp.i
.PHONY : ext/nanobind/src/nb_enum.cpp.i

ext/nanobind/src/nb_enum.s: ext/nanobind/src/nb_enum.cpp.s
.PHONY : ext/nanobind/src/nb_enum.s

# target to generate assembly for a file
ext/nanobind/src/nb_enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_enum.cpp.s
.PHONY : ext/nanobind/src/nb_enum.cpp.s

ext/nanobind/src/nb_func.o: ext/nanobind/src/nb_func.cpp.o
.PHONY : ext/nanobind/src/nb_func.o

# target to build an object file
ext/nanobind/src/nb_func.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_func.cpp.o
.PHONY : ext/nanobind/src/nb_func.cpp.o

ext/nanobind/src/nb_func.i: ext/nanobind/src/nb_func.cpp.i
.PHONY : ext/nanobind/src/nb_func.i

# target to preprocess a source file
ext/nanobind/src/nb_func.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_func.cpp.i
.PHONY : ext/nanobind/src/nb_func.cpp.i

ext/nanobind/src/nb_func.s: ext/nanobind/src/nb_func.cpp.s
.PHONY : ext/nanobind/src/nb_func.s

# target to generate assembly for a file
ext/nanobind/src/nb_func.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_func.cpp.s
.PHONY : ext/nanobind/src/nb_func.cpp.s

ext/nanobind/src/nb_internals.o: ext/nanobind/src/nb_internals.cpp.o
.PHONY : ext/nanobind/src/nb_internals.o

# target to build an object file
ext/nanobind/src/nb_internals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_internals.cpp.o
.PHONY : ext/nanobind/src/nb_internals.cpp.o

ext/nanobind/src/nb_internals.i: ext/nanobind/src/nb_internals.cpp.i
.PHONY : ext/nanobind/src/nb_internals.i

# target to preprocess a source file
ext/nanobind/src/nb_internals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_internals.cpp.i
.PHONY : ext/nanobind/src/nb_internals.cpp.i

ext/nanobind/src/nb_internals.s: ext/nanobind/src/nb_internals.cpp.s
.PHONY : ext/nanobind/src/nb_internals.s

# target to generate assembly for a file
ext/nanobind/src/nb_internals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_internals.cpp.s
.PHONY : ext/nanobind/src/nb_internals.cpp.s

ext/nanobind/src/nb_ndarray.o: ext/nanobind/src/nb_ndarray.cpp.o
.PHONY : ext/nanobind/src/nb_ndarray.o

# target to build an object file
ext/nanobind/src/nb_ndarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_ndarray.cpp.o
.PHONY : ext/nanobind/src/nb_ndarray.cpp.o

ext/nanobind/src/nb_ndarray.i: ext/nanobind/src/nb_ndarray.cpp.i
.PHONY : ext/nanobind/src/nb_ndarray.i

# target to preprocess a source file
ext/nanobind/src/nb_ndarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_ndarray.cpp.i
.PHONY : ext/nanobind/src/nb_ndarray.cpp.i

ext/nanobind/src/nb_ndarray.s: ext/nanobind/src/nb_ndarray.cpp.s
.PHONY : ext/nanobind/src/nb_ndarray.s

# target to generate assembly for a file
ext/nanobind/src/nb_ndarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_ndarray.cpp.s
.PHONY : ext/nanobind/src/nb_ndarray.cpp.s

ext/nanobind/src/nb_static_property.o: ext/nanobind/src/nb_static_property.cpp.o
.PHONY : ext/nanobind/src/nb_static_property.o

# target to build an object file
ext/nanobind/src/nb_static_property.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_static_property.cpp.o
.PHONY : ext/nanobind/src/nb_static_property.cpp.o

ext/nanobind/src/nb_static_property.i: ext/nanobind/src/nb_static_property.cpp.i
.PHONY : ext/nanobind/src/nb_static_property.i

# target to preprocess a source file
ext/nanobind/src/nb_static_property.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_static_property.cpp.i
.PHONY : ext/nanobind/src/nb_static_property.cpp.i

ext/nanobind/src/nb_static_property.s: ext/nanobind/src/nb_static_property.cpp.s
.PHONY : ext/nanobind/src/nb_static_property.s

# target to generate assembly for a file
ext/nanobind/src/nb_static_property.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_static_property.cpp.s
.PHONY : ext/nanobind/src/nb_static_property.cpp.s

ext/nanobind/src/nb_type.o: ext/nanobind/src/nb_type.cpp.o
.PHONY : ext/nanobind/src/nb_type.o

# target to build an object file
ext/nanobind/src/nb_type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_type.cpp.o
.PHONY : ext/nanobind/src/nb_type.cpp.o

ext/nanobind/src/nb_type.i: ext/nanobind/src/nb_type.cpp.i
.PHONY : ext/nanobind/src/nb_type.i

# target to preprocess a source file
ext/nanobind/src/nb_type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_type.cpp.i
.PHONY : ext/nanobind/src/nb_type.cpp.i

ext/nanobind/src/nb_type.s: ext/nanobind/src/nb_type.cpp.s
.PHONY : ext/nanobind/src/nb_type.s

# target to generate assembly for a file
ext/nanobind/src/nb_type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/nb_type.cpp.s
.PHONY : ext/nanobind/src/nb_type.cpp.s

ext/nanobind/src/trampoline.o: ext/nanobind/src/trampoline.cpp.o
.PHONY : ext/nanobind/src/trampoline.o

# target to build an object file
ext/nanobind/src/trampoline.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/trampoline.cpp.o
.PHONY : ext/nanobind/src/trampoline.cpp.o

ext/nanobind/src/trampoline.i: ext/nanobind/src/trampoline.cpp.i
.PHONY : ext/nanobind/src/trampoline.i

# target to preprocess a source file
ext/nanobind/src/trampoline.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/trampoline.cpp.i
.PHONY : ext/nanobind/src/trampoline.cpp.i

ext/nanobind/src/trampoline.s: ext/nanobind/src/trampoline.cpp.s
.PHONY : ext/nanobind/src/trampoline.s

# target to generate assembly for a file
ext/nanobind/src/trampoline.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nanobind-static.dir/build.make CMakeFiles/nanobind-static.dir/ext/nanobind/src/trampoline.cpp.s
.PHONY : ext/nanobind/src/trampoline.cpp.s

src/correa.o: src/correa.cpp.o
.PHONY : src/correa.o

# target to build an object file
src/correa.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_correa.dir/build.make CMakeFiles/_correa.dir/src/correa.cpp.o
.PHONY : src/correa.cpp.o

src/correa.i: src/correa.cpp.i
.PHONY : src/correa.i

# target to preprocess a source file
src/correa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_correa.dir/build.make CMakeFiles/_correa.dir/src/correa.cpp.i
.PHONY : src/correa.cpp.i

src/correa.s: src/correa.cpp.s
.PHONY : src/correa.s

# target to generate assembly for a file
src/correa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/_correa.dir/build.make CMakeFiles/_correa.dir/src/correa.cpp.s
.PHONY : src/correa.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 2DShape"
	@echo "... Comp2DShapes"
	@echo "... Comp2DShapesFocal"
	@echo "... _correa"
	@echo "... nanobind-static"
	@echo "... ext/nanobind/src/common.o"
	@echo "... ext/nanobind/src/common.i"
	@echo "... ext/nanobind/src/common.s"
	@echo "... ext/nanobind/src/error.o"
	@echo "... ext/nanobind/src/error.i"
	@echo "... ext/nanobind/src/error.s"
	@echo "... ext/nanobind/src/implicit.o"
	@echo "... ext/nanobind/src/implicit.i"
	@echo "... ext/nanobind/src/implicit.s"
	@echo "... ext/nanobind/src/nb_enum.o"
	@echo "... ext/nanobind/src/nb_enum.i"
	@echo "... ext/nanobind/src/nb_enum.s"
	@echo "... ext/nanobind/src/nb_func.o"
	@echo "... ext/nanobind/src/nb_func.i"
	@echo "... ext/nanobind/src/nb_func.s"
	@echo "... ext/nanobind/src/nb_internals.o"
	@echo "... ext/nanobind/src/nb_internals.i"
	@echo "... ext/nanobind/src/nb_internals.s"
	@echo "... ext/nanobind/src/nb_ndarray.o"
	@echo "... ext/nanobind/src/nb_ndarray.i"
	@echo "... ext/nanobind/src/nb_ndarray.s"
	@echo "... ext/nanobind/src/nb_static_property.o"
	@echo "... ext/nanobind/src/nb_static_property.i"
	@echo "... ext/nanobind/src/nb_static_property.s"
	@echo "... ext/nanobind/src/nb_type.o"
	@echo "... ext/nanobind/src/nb_type.i"
	@echo "... ext/nanobind/src/nb_type.s"
	@echo "... ext/nanobind/src/trampoline.o"
	@echo "... ext/nanobind/src/trampoline.i"
	@echo "... ext/nanobind/src/trampoline.s"
	@echo "... src/correa.o"
	@echo "... src/correa.i"
	@echo "... src/correa.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

